#!/bin/bash
# Author: R D Bharti
# Date Created: 12/11/2022
# Last Modified: 12/11/2022

# Description
# This script should backup all the files in \
# your home directory and save them all in a .tar archive. 

# Usage
# backup_script-Project

# command- tar -czvf file.tar.gz directoryToTar

tar -czvf /tmp/homeDirBackup_"$(date +%d-%m-%Y_%H-%M-%S)".tar.gz ~/* 2>/dev/null

