#!/bin/bash
# Author: R D Bharti
# Date Created: 12/11/2022
# Last Modified: 12/11/2022

# Description
# Prints Text on Screen

# Usage
# our_first_script

echo "This is my First Script"
exit 0 # exit-code
