#!/bin/bash

echo $(( 4 + 2)) # 6

x=8
y=9

#with $ sign
echo $(( $x + $y ))

# without $ sign
echo $(( x + y )) # 17
echo $(( x - y )) # 1
echo $(( x * y )) # 72
echo $(( x / y )) # 0


# Multiple Operators
echo "Multiple Operators"

echo $(( 2 + 3 * 4 )) # 14

echo $(( (2 + 3) * 4 ))

# Exponents
echo "Exponent"

echo $(( 4 ** 2 )) # 16

# Modulo

echo $(( 5 % 2 )) # 1

echo $(( 4 % 2 )) # 0

# Decimal
# echo $(( 2.5 + 3 )) # syntax error: invalid arithmetic operator (error token is ".5 + 3 ")

# bc commands
echo "BC COMMANDS"
echo "5/2" | bc

echo "scale=2; 5/2" |bc 

echo "5^2" | bc # 25